const actionsTypes = {
	//Routers Actions
	GET_ROUTER: "GET_ROUTER",
	ADD_ROUTER: "ADD_ROUTER",
	REMOVE_ROUTER: "REMOVE_ROUTER",
	SET_ROUTER: "SET_ROUTER",
	//Routes Actions
	GET_ROUTES: "GET_ROUTES",
	ADD_ROUTE: "ADD_ROUTE",
	REMOVE_ROUTE: "REMOVE_ROUTE",
	SET_ROUTE: "SET_ROUTE",
	//Actual Route Actions
	GET_ACTUAL_ROUTE: "GET_ACTUAL_ROUTE",
	SET_ACTUAL_ROUTE: "SET_ACTUAL_ROUTE",
};

export default actionsTypes;
